/*
 Generated by typeshare 1.9.2
*/

export interface LoginPayload {
	email: string;
	password: string;
}

export interface LoginResponsePayload {
	logged_in: boolean;
}

export interface RegisterPayload {
	email: string;
	email_verification_code: string;
	password: string;
	confirm_password: string;
	invite_code: string;
}

export interface ForgotPasswordPayload {
	email: string;
	email_verification_code: string;
	password: string;
	confirm_password: string;
}

export interface VerifyEmailPayload {
	email: string;
}

export interface ServerStatusPayload {
	server: string;
	status: string;
}

export interface UserProfilePayload {
	email: string;
	email_verified: boolean;
	created_at: string;
	updated_at: string;
	email_expiration_reminder: boolean;
	email_data_reminder: boolean;
}

export enum UserTransactionStatusEnum {
	Unpaid = "Unpaid",
	Pending = "Pending",
	Completed = "Completed",
	Failed = "Failed",
	Cancelled = "Cancelled",
}

export interface UserTransactionPayload {
	transaction_id: number;
	amount: number;
	transaction_date: string;
	payment_method?: string;
	status: UserTransactionStatusEnum;
	stripe_payment_intent_id?: string;
	created_at: string;
	updated_at: string;
	plan_id?: number;
	description?: string;
}

export enum PlanStatusEnum {
	Active = "Active",
	Expired = "Expired",
	Cancelled = "Cancelled",
}

export interface PlanDetailsPayload {
	expiration: string;
	status: PlanStatusEnum;
	dataUsed: number;
	dataLimit: number;
}

export interface AnnouncementPayload {
	id: number;
	title: string;
	date: string;
	content: string;
}

export interface PlanPayload {
	id: number;
	name: string;
	price: number;
	data_limit?: number;
	duration_days: number;
	description?: string;
}

export interface CreateOrderPayload {
	plan_id: number;
}

export interface CreateOrderResponsePayload {
	order_id: number;
	payment_intent_client_secret: string;
}

export interface AdminUser {
	id: number;
	email: string;
	admin: boolean;
	created_at: DateTime<Utc>;
	updated_at: DateTime<Utc>;
}

export enum ServerStatusEnum {
	Online = "Online",
	Degraded = "Degraded",
	Unreachable = "Unreachable",
}

