/*
 Generated by typeshare 1.9.2
*/

export interface LoginPayload {
	email: string;
	password: string;
}

export interface RegisterPayload {
	email: string;
	email_verification_code: string;
	password: string;
	confirm_password: string;
	invite_code: string;
}

export interface ForgotPasswordPayload {
	email: string;
	email_verification_code: string;
	password: string;
	confirm_password: string;
}

export interface VerifyEmailPayload {
	email: string;
}

