/*
 Generated by typeshare 1.13.2
*/

export interface AdminCreateAnnouncement {
	title: string;
	content: string;
}

export interface AdminUser {
	id: number;
	email: string;
	marzban_username?: string;
	admin: boolean;
	created_at: number;
	updated_at: number;
}

export interface AdminUserModify {
	email: string;
	marzban_username?: string;
	admin: boolean;
}

export interface AnnouncementPayload {
	id: number;
	title: string;
	date: string;
	content: string;
}

export interface ChangePasswordPayload {
	old_password: string;
	new_password: string;
	confirm_password: string;
}

export interface CreateOrderPayload {
	plan_id: number;
}

export interface CreateOrderResponsePayload {
	order_id: number;
	payment_intent_client_secret: string;
}

export interface ForgotPasswordPayload {
	email: string;
	email_verification_code: string;
	password: string;
	confirm_password: string;
}

export interface LoginPayload {
	email: string;
	password: string;
}

export interface LoginResponsePayload {
	logged_in: boolean;
}

export interface NewPlanPayload {
	name: string;
	price: number;
	data_limit?: number;
	duration_days: number;
	description?: string;
}

export interface PasswordFeedbackPayload {
	warning?: string;
	suggestions: string[];
}

export enum PlanStatusEnum {
	Active = "Active",
	Disabled = "Disabled",
	Limited = "Limited",
	Expired = "Expired",
	OnHold = "OnHold",
}

export interface PlanDetailsPayload {
	expiration?: number;
	status: PlanStatusEnum;
	dataUsed: number;
	dataLimit?: number;
}

export interface PlanPayload {
	id: number;
	name: string;
	price: number;
	data_limit?: number;
	duration_days: number;
	description?: string;
}

export interface RegisterPayload {
	email: string;
	email_verification_code: string;
	password: string;
	confirm_password: string;
	invite_code: string;
}

export interface RequestCodePayload {
	email: string;
}

export interface ServerStatusPayload {
	server: string;
	status: string;
}

export interface UserProfilePayload {
	email: string;
	created_at: string;
	updated_at: string;
	email_expiration_reminder: boolean;
	email_data_reminder: boolean;
}

export interface UserProfileSettingsChangePayload {
	email_expiration_reminder?: boolean;
	email_data_reminder?: boolean;
}

export enum UserTransactionStatusEnum {
	Canceled = "Canceled",
	Processing = "Processing",
	RequiresAction = "RequiresAction",
	RequiresCapture = "RequiresCapture",
	RequiresConfirmation = "RequiresConfirmation",
	RequiresPaymentMethod = "RequiresPaymentMethod",
	Succeeded = "Succeeded",
	Refunded = "Refunded",
}

export interface UserTransactionPayload {
	id: number;
	user_id: number;
	plan_id: number;
	amount: number;
	status: UserTransactionStatusEnum;
	stripe_payment_intent_id?: string;
	created_at: number;
	updated_at: number;
}

export interface VerifyEmailPayload {
	email: string;
	email_verification_code: string;
}

export enum ServerStatusEnum {
	Online = "Online",
	Degraded = "Degraded",
	Unreachable = "Unreachable",
}

