-- Add migration script here
ALTER TABLE transactions
MODIFY created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
MODIFY updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL;