-- Add migration script here
ALTER TABLE users
MODIFY id INT NOT NULL AUTO_INCREMENT,
MODIFY marzban_username VARCHAR(255) NOT NULL,
MODIFY email VARCHAR(255) NOT NULL,
MODIFY password_hash VARCHAR(255) NOT NULL,
MODIFY password_salt VARCHAR(255) NOT NULL,
MODIFY is_admin BOOLEAN NOT NULL DEFAULT FALSE,
MODIFY created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
MODIFY updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;