// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminUserCreate = { email: string, marzban_username: string | null, password: string, admin: boolean, };
