// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminUserModify = { email: string, marzban_username: string | null, admin: boolean, };
