// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Announcement = { id: number, title: string, date: string, content: string, };
