// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreateOrderResponse = { order_id: number, payment_intent_client_secret: string, };
