// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NewPlan = { name: string, price: string, data_limit: number | null, duration_days: bigint, description: string | null, };
