// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Plan = { id: bigint, name: string, price: number, data_limit: number | null, duration_days: bigint, description: string | null, };
