// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserProfile = { email: string, created_at: string, updated_at: string, email_expiration_reminder: boolean, email_data_reminder: boolean, };
