// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserTransactionStatus } from "./UserTransactionStatus";

export type UserTransaction = { id: bigint, user_id: bigint, plan_id: bigint, amount: number, status: UserTransactionStatus, stripe_payment_intent_id: string | null, created_at: bigint, updated_at: bigint, };
