// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserProfileSettingsChange = { email_expiration_reminder: boolean | null, email_data_reminder: boolean | null, };
