// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UserTransactionStatusEnum } from "./UserTransactionStatusEnum";

export type UserTransactionPayload = { id: bigint, user_id: bigint, plan_id: bigint, amount: number, status: UserTransactionStatusEnum, stripe_payment_intent_id: string | null, created_at: bigint, updated_at: bigint, };
