// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminUser = { id: number, email: string, marzban_username: string | null, admin: boolean, created_at: bigint, updated_at: bigint, };
