// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ForgotPasswordPayload = { email: string, email_verification_code: string, password: string, confirm_password: string, };
