// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlanStatusEnum } from "./PlanStatusEnum";

export type PlanDetailsPayload = { expiration: bigint | null, status: PlanStatusEnum, dataUsed: bigint, dataLimit: bigint | null, };
